"""add performed_by columns

Revision ID: 4b7b05aeb31b
Revises: 2ee47e9b24c4
Create Date: 2026-07-07 19:10:45.508789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7b05aeb31b'
down_revision: Union[str, Sequence[str], None] = '2ee47e9b24c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('performed_by_id', sa.Integer(), nullable=True))
    op.add_column('activity_logs', sa.Column('performed_by_name', sa.String(length=100), nullable=True))
    op.add_column('activity_logs', sa.Column('performed_by_role', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('activity_logs_student_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'activity_logs', 'users', ['performed_by_id'], ['id'])
    op.drop_constraint(op.f('documents_student_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['student_id'], ['id'])
    op.drop_constraint(op.f('enrollments_student_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_student_id_fkey'), 'enrollments', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_student_id_fkey'), 'documents', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_student_id_fkey'), 'activity_logs', 'students', ['student_id'], ['id'])
    op.drop_column('activity_logs', 'performed_by_role')
    op.drop_column('activity_logs', 'performed_by_name')
    op.drop_column('activity_logs', 'performed_by_id')
    # ### end Alembic commands ###
