"""add changes column to activity_logs

Revision ID: 524743605d90
Revises: baae90afc242
Create Date: 2026-06-24 09:20:02.736072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524743605d90'
down_revision: Union[str, Sequence[str], None] = 'baae90afc242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('changes', sa.JSON(), nullable=True))
    op.alter_column('activity_logs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('activity_logs', 'changes')
    # ### end Alembic commands ###
