"""add documents_id to active_logs

Revision ID: 61696179f334
Revises: 065d7482c5ae
Create Date: 2026-07-02 06:29:41.982863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61696179f334'
down_revision: Union[str, Sequence[str], None] = '065d7482c5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'document_id')
    # ### end Alembic commands ###
