"""Added indexing for speed optimization

Revision ID: b573f79bb3b9
Revises: f821edad31c1
Create Date: 2026-07-21 05:11:20.452533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b573f79bb3b9'
down_revision: Union[str, Sequence[str], None] = 'f821edad31c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_course_id'), 'activity_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_document_id'), 'activity_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_performed_by_id'), 'activity_logs', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_student_id'), 'activity_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_student_id'), 'documents', ['student_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.drop_constraint(op.f('students_email_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_unique_constraint(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_documents_student_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_activity_logs_student_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_performed_by_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_document_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_course_id'), table_name='activity_logs')
    # ### end Alembic commands ###
