"""add is_active to students

Revision ID: baae90afc242
Revises: 9bc452942575
Create Date: 2026-06-23 11:11:15.068488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baae90afc242'
down_revision: Union[str, Sequence[str], None] = '9bc452942575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('students', 'photo_url',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'photo_url',
               existing_type=sa.String(length=500),
               type_=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
