services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9560Navneet
      POSTGRES_DB: student_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./media:/app/media

volumes:
  postgres_data: